[package]
name = "sablast"
version = "0.1.0"
edition = "2021"
authors = ["Tommi Mäklin <tommi@maklin.fi>"]
description = "Spectral Burrows-Wheeler transform accelerated local alignment search"
readme = "README.md"
homepage = "https://github.com/tmaklin/sablast"
repository = "https://github.com/tmaklin/sablast"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
## core
jseqio = "0.1.2"
sbwt = "0.3.1"

## cli
clap = { version = "4.4.18", features = ["derive"] }

## logging
log = "0.4.20"
stderrlog = "0.6.0"
