name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_rust:
    name: Build and test Rust code

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - stable

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
