name: Build and test

on:
  push:
    branches-ignore:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_rust:
    name: Build and test Rust code

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - stable

    steps:
    - uses: actions/checkout@v4

    - name: Setup toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - name: Build binary
      run: cargo build --verbose

    - name: Run unit and integration tests
      run: cargo test --verbose

    - name: Run documenation examples as tests
      run: cargo test --doc --verbose
